development:
  :address: smtp.elegend.net
  :port: 26
  :Domain: mail.elegend.net
  :authentication: plain
  :user_name: no-reply@elegend.net
  :password: eNO-REPLY_0601
  :enable_starttls_auto: false  

production:
  :address: smtp.elegend.net
  :port: 26
  :Domain: mail.elegend.net
  :authentication: plain
  :user_name: no-reply@elegend.net
  :password: eNO-REPLY_0601
  :enable_starttls_auto: false   
